name: ecommerce_c17_online
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0
dependencies:
  dio: ^5.9.1
  pretty_dio_logger: ^1.4.0
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  loader_overlay: ^5.0.0
  shared_preferences: ^2.5.4
  get_it: ^9.2.1
  injectable: ^2.7.1+4
  cached_network_image:
  carousel_slider_plus:
  flutter:
    sdk: flutter
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore:
  smooth_page_indicator:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  injectable_generator: ^2.12.0
  build_runner: ^2.11.1
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf


